spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
jwt:
  # 签发人
  issuer: ts
  # 秘钥
  secret: sC15x+Syan4+6E9T7NoG7oU2CNEiCSRkKIeX2tbMReJtXsVsj0lhGIGZGIrmuTqmnbnIDA2Ygm//ys5lf4uUPw==
  # token 过期时间（单位：分钟） 1*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer